/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "inverse-primary": "#68dba9",
        "on-tertiary-container": "#f7fff2",
        "on-surface": "#0b1c30",
        "secondary-container": "#316bf3",
        "on-tertiary-fixed": "#002109",
        "on-background": "#0b1c30",
        "surface-container-low": "#eff4ff",
        "surface-container-lowest": "#ffffff",
        "inverse-on-surface": "#eaf1ff",
        "error-container": "#ffdad6",
        "surface-dim": "#cbdbf5",
        "primary": "#006948",
        "primary-hover": "#047857",
        "outline": "#6d7a72",
        "on-tertiary-fixed-variant": "#005320",
        "on-primary": "#ffffff",
        "surface-container-high": "#dce9ff",
        "surface-variant": "#d3e4fe",
        "on-primary-fixed-variant": "#005137",
        "background": "#f8f9ff",
        "surface": "#f8f9ff",
        "on-secondary-container": "#fefcff",
        "on-secondary-fixed-variant": "#003ea8",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "tertiary-fixed": "#7ffc97",
        "on-secondary-fixed": "#00174b",
        "tertiary-fixed-dim": "#62df7d",
        "on-primary-container": "#f5fff7",
        "primary-container": "#00855d",
        "on-surface-variant": "#3d4a42",
        "surface-tint": "#006c4a",
        "surface-bright": "#f8f9ff",
        "secondary-fixed-dim": "#b4c5ff",
        "on-secondary": "#ffffff",
        "on-tertiary": "#ffffff",
        "tertiary": "#006b2c",
        "outline-variant": "#bccac0",
        "error": "#ba1a1a",
        "tertiary-container": "#00873a",
        "primary-fixed-dim": "#68dba9",
        "inverse-surface": "#213145",
        "on-primary-fixed": "#002114",
        "secondary": "#0051d5",
        "surface-container-highest": "#d3e4fe",
        "secondary-fixed": "#dbe1ff",
        "primary-fixed": "#85f8c4",
        "surface-container": "#e5eeff",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      spacing: {
        "gutter-mobile": "0.75rem",
        "space-2xl": "2.5rem",
        "space-2xs": "0.25rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-xs": "0.5rem",
        gutter: "1.5rem",
        "margin-mobile": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        margin: "2rem",
      },
      fontFamily: {
        "body-md": ["Inter", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "data-table": ["Inter", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "data-metric-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "data-metric-lg": ["Plus Jakarta Sans", "sans-serif"],
      },
      fontSize: {
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg": ["24px", { lineHeight: "32px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", fontWeight: "600" }],
        "headline-xl-mobile": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "headline-xl": ["32px", { lineHeight: "40px", fontWeight: "700" }],
        "data-table": ["13px", { lineHeight: "18px", fontWeight: "500" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "data-metric-md": ["18px", { lineHeight: "24px", fontWeight: "700" }],
        "headline-sm": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-sm": ["11px", { lineHeight: "14px", fontWeight: "500" }],
        "data-metric-lg": ["28px", { lineHeight: "34px", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};
