'use client';
import { Suspense, useEffect, useMemo, useState } from 'react';
import { useSearchParams } from 'next/navigation';
import Link from 'next/link';
import { useTrades } from '../../context/TradeContext';
import { DailyJournal, EmotionalState } from '../../types';
import { localDate } from '../../lib/dates';
import { formatCurrency } from '../../lib/utils';
import { fieldClass } from '../../components/common/ChargeEditor';

export default function JournalPage() { return <Suspense fallback={<p>Loading journal…</p>}><Journal /></Suspense>; }
function Journal() {
  const params = useSearchParams(), { user, accounts, trades, journals, saveJournal } = useTrades();
  const validDate = (value: string | null) => value && /^\d{4}-\d{2}-\d{2}$/.test(value) && !Number.isNaN(new Date(value).getTime()) ? value : localDate();
  const [date, setDate] = useState(validDate(params.get('date'))), [dirty, setDirty] = useState(false), [notice, setNotice] = useState('');
  const empty = (date: string): DailyJournal => ({ id: `dj_${date}`, date, preMarketNotes: '', postMarketNotes: '', emotionalState: 'Calm', starRating: 0, rulesFollowed: true, mindsetTags: [], mistakeTags: [] });
  const [draft, setDraft] = useState<DailyJournal>(journals[date] || empty(date));
  const saved = journals[date];
  useEffect(() => { setDraft(saved || empty(date)); setDirty(false); setNotice(''); }, [date, saved]);
  const changeDate = (next: string) => { if (!next || (dirty && !confirm('Leave this day without saving your journal changes?'))) return; setDate(next); };
  const change = (next: Partial<DailyJournal>) => { setDraft({ ...draft, ...next }); setDirty(true); setNotice(''); };
  const daily = useMemo(() => trades.filter(t => t.date === date), [trades, date]), closed = daily.filter(t => t.status === 'CLOSED');
  const currencies = new Set(closed.map(t => accounts.find(a => a.id === t.accountId)?.currency || user.baseCurrency));
  const currency = accounts.find(a => a.id === closed[0]?.accountId)?.currency || user.baseCurrency;
  const save = (e: React.FormEvent) => { e.preventDefault(); try { saveJournal({ ...draft, date, tradesCount: daily.length, dayPnl: currencies.size > 1 ? undefined : closed.reduce((sum, t) => sum + t.netPnl, 0) }); setDirty(false); setNotice('Journal saved.'); } catch { setNotice('Could not save journal. Check browser storage.'); } };
  const shift = (days: number) => { const next = new Date(`${date}T12:00:00`); next.setDate(next.getDate() + days); changeDate(localDate(next)); };
  return <div className="space-y-5 max-w-5xl mx-auto"><div><h1 className="page-title">Daily journal</h1><p className="text-sm text-outline mt-1">Plan your session and reflect on your trades.</p></div>
    <div className="grid grid-cols-[44px_1fr_44px] sm:flex gap-2 items-center"><button className="btn-secondary px-2" aria-label="Previous day" onClick={() => shift(-1)}>←</button><label className="sr-only" htmlFor="journal-date">Journal date</label><input id="journal-date" className={`${fieldClass} sm:max-w-[220px]`} type="date" value={date} onChange={e => changeDate(e.target.value)} /><button className="btn-secondary px-2" aria-label="Next day" onClick={() => shift(1)}>→</button><button className="btn-secondary col-span-3" onClick={() => changeDate(localDate())}>Today</button></div>
    <div className="grid grid-cols-2 sm:grid-cols-3 gap-3"><div className="card"><p className="text-xs text-outline">Recorded trades</p><p className="text-xl mt-2">{daily.length}</p></div><div className="card"><p className="text-xs text-outline">Realized P&amp;L</p><p className="text-xl mt-2 tabular-nums">{currencies.size > 1 ? 'Mixed currencies' : formatCurrency(closed.reduce((sum, t) => sum + t.netPnl, 0), currency, true)}</p></div><div className="card"><p className="text-xs text-outline">Win rate</p><p className="text-xl mt-2">{closed.length ? `${Math.round(closed.filter(t => t.netPnl > 0).length / closed.length * 100)}%` : '—'}</p></div></div>
    <form className="card space-y-5" onSubmit={save}><label className="field-label">Pre-market plan<textarea className={fieldClass} rows={4} value={draft.preMarketNotes || ''} onChange={e => change({ preMarketNotes: e.target.value })} placeholder="Your plan, levels and rules for the day" /></label><label className="field-label">Post-market reflections<textarea className={fieldClass} rows={5} value={draft.postMarketNotes} onChange={e => change({ postMarketNotes: e.target.value })} placeholder="What worked? What would you change?" /></label><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><label className="field-label">Emotion<select className={fieldClass} value={draft.emotionalState} onChange={e => change({ emotionalState: e.target.value as EmotionalState })}>{['Calm', 'Confident', 'Fear', 'FOMO', 'Greedy', 'Revenge'].map(e => <option key={e}>{e}</option>)}</select></label><label className="field-label">Session rating<select className={fieldClass} value={draft.starRating} onChange={e => change({ starRating: Number(e.target.value) })}><option value="0">Not rated</option>{[1, 2, 3, 4, 5].map(n => <option key={n} value={n}>{n} / 5</option>)}</select></label></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={draft.rulesFollowed} onChange={e => change({ rulesFollowed: e.target.checked })} />I followed my trading rules</label><div><p className="text-sm mb-2">Mistakes to review</p><div className="flex flex-wrap gap-2">{['Early exit', 'Overtrading', 'Ignored stop loss', 'Revenge trade', 'Poor entry'].map(tag => <button type="button" key={tag} aria-pressed={draft.mistakeTags.includes(tag)} className={`btn-secondary ${draft.mistakeTags.includes(tag) ? 'bg-error/10 text-error border-error/20' : ''}`} onClick={() => change({ mistakeTags: draft.mistakeTags.includes(tag) ? draft.mistakeTags.filter(t => t !== tag) : [...draft.mistakeTags, tag] })}>{tag}</button>)}</div></div>{notice && <p role="status" className="text-sm text-primary">{notice}</p>}<button className="btn-primary w-full sm:w-auto">Save journal</button></form>
    <section className="card space-y-3"><h2 className="section-title">Trades for this day</h2>{daily.length ? daily.map(t => <Link key={t.id} href={`/trades/${t.id}`} className="flex justify-between gap-3 border-b border-surface-container py-3 text-sm"><span className="break-words">{t.instrument}</span><span className="tabular-nums shrink-0">{t.status === 'OPEN' ? 'Open' : formatCurrency(t.netPnl, accounts.find(a => a.id === t.accountId)?.currency || user.baseCurrency, true)}</span></Link>) : <p className="text-sm text-outline">No recorded trades.</p>}</section>
  </div>;
}
