import Link from 'next/link';
import { PublicShell } from './PublicShell';
import { topics } from '../../lib/public-content';
import { SITE_URL, serializeJsonLd } from '../../lib/seo';
export function TopicPage({slug}: {slug: keyof typeof topics}) {
 const topic = topics[slug];
 const schema = {'@context':'https://schema.org','@graph':[{'@type':'WebPage',url:SITE_URL+'/'+slug,name:topic.title,description:topic.description},{'@type':'BreadcrumbList',itemListElement:[{'@type':'ListItem',position:1,name:'Home',item:SITE_URL},{'@type':'ListItem',position:2,name:topic.title,item:SITE_URL+'/'+slug}]},{'@type':'FAQPage',mainEntity:topic.faqs.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))}]};
 return <PublicShell><script type="application/ld+json" dangerouslySetInnerHTML={{__html:serializeJsonLd(schema)}}/><div className="max-w-4xl mx-auto"><p className="text-xs tracking-widest font-semibold text-primary mb-4">RECORD. REVIEW. IMPROVE YOUR PROCESS.</p><h1 className="text-3xl sm:text-5xl font-semibold tracking-tight leading-tight">{topic.title}</h1><p className="text-base sm:text-lg text-on-surface-variant leading-relaxed mt-6">{topic.intro}</p><div className="flex flex-wrap gap-3 mt-7"><Link href="/onboarding" className="btn-primary">Start your journal</Link><Link href="/brokerage-calculator" className="btn-secondary">Calculate charges</Link></div><div className="space-y-6 mt-12">{topic.sections.map(([title,text])=><section key={title} className="card"><h2 className="section-title">{title}</h2><p className="text-on-surface-variant leading-relaxed mt-3">{text}</p></section>)}</div><section className="mt-12"><h2 className="text-2xl font-semibold mb-5">Frequently asked questions</h2><div className="space-y-4">{topic.faqs.map(([q,a])=><details className="card" key={q}><summary className="font-medium cursor-pointer">{q}</summary><p className="mt-3 text-on-surface-variant leading-relaxed">{a}</p></details>)}</div></section><nav className="flex flex-wrap gap-5 mt-10 text-primary text-sm" aria-label="Related resources"><Link href="/guides/trading-journal-template">Journal template →</Link><Link href="/guides/how-to-calculate-net-pnl">Net P&amp;L guide →</Link><Link href="/guides/trading-performance-metrics">Performance metrics →</Link></nav></div></PublicShell>;
}

